module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

replace github.com/nanmu42/etherscan-api => github.com/cryptoriums/etherscan-api v1.3.1-0.20210819094440-d2f683c2d35c

require github.com/cryptoriums/contraget v0.0.0-20210819100247-63447b75d6f9 // cmd/contraget
