apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "grafana.fullname" . }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: {{ .Values.grafana.storageClassName }}
  resources:
    requests:
      storage: {{ print $.Values.prometheus.storage "Gi" }}

