{{- range $index := .Values.command }}
{{- $val := dict "command" $index }}
{{- $commandName := printf "%s-%s" (include "telliot.fullname" $) (include "telliot.commandName" $val) | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $commandName }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ print $.Values.storage "Gi" }}
{{- end }}