{{- range $index := .Values.command }}
{{- $val := dict "command" $index }}
{{- $commandName := printf "%s-%s" (include "telliot.fullname" $) (include "telliot.commandName" $val) | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $commandName }}
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  {{- $commandPath := printf "%s/%s" "files" ( (get $val "command")| lower) }}
  {{- $path := "files" }}
  {{- $commandConfig := $.Files.Glob (printf "%s/%s" $commandPath ".env") }}
  {{- $file := coalesce ($.Files.Get (printf "%s/%s" $path ".env") | trimSuffix "\n") ($.Files.Get (printf "%s/%s" $commandPath ".env") | trimSuffix "\n") }}
  {{- range $line := splitList "\n" $file }}
  {{- if and (contains "=" $line) (not (hasPrefix "#" $line)) }}
  {{- $kv := splitList "=" $line }}
  {{- $commentSafeValue := first (splitList "#" (last $kv)) }}
  {{ first $kv }}: {{ b64enc $commentSafeValue }}
  {{- end }}
  {{- end }}
{{- end }}