{{- range $index := .Values.command }}
{{- $val := dict "command" $index }}
{{- $commandName := printf "%s-%s" (include "telliot.fullname" $) (include "telliot.commandName" $val) | trunc 63 | trimSuffix "-" }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $commandName }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $commandName }}
spec:
  selector:
    app: {{ $commandName }}
  ports:
  - name: {{ $commandName }}
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.container.port }}
{{- end }}